### ISSUE TITLE
[BUG REPORT] Empty page due to react javascript error

### ISSUE THREAD

**Issue by jchatel** [bitfinexcom/bfx-report-electron#118]
Going to beginning snapshot leads to an empty page, opening the console shots problem in the react code:

react-dom.production.min.js:209 TypeError: Cannot read property 'params' of undefined
    at Function.mapToProps (Snapshot.container.js:16)
    at o (wrapMapToProps.js:41)
    at Function.o.mapToProps (wrapMapToProps.js:50)
    at o (wrapMapToProps.js:41)
    at selectorFactory.js:22
    at connectAdvanced.js:319
    at Object.useMemo (react-dom.production.min.js:165)
    at t.useMemo (react.production.min.js:25)
    at y (connectAdvanced.js:304)
    at Ji (react-dom.production.min.js:153)
rp @ react-dom.production.min.js:209
n.callback @ react-dom.production.min.js:226
di @ react-dom.production.min.js:131
bp @ react-dom.production.min.js:212
Wa @ react-dom.production.min.js:255
t.unstable_runWithPriority @ scheduler.production.min.js:19
Gr @ react-dom.production.min.js:122
qa @ react-dom.production.min.js:248
pa @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Gr @ react-dom.production.min.js:122
$r @ react-dom.production.min.js:123
Qr @ react-dom.production.min.js:122
aa @ react-dom.production.min.js:240
notify @ Subscription.js:19
t.notifyNestedSubs @ Subscription.js:90
t.handleChangeWrapper @ Subscription.js:95
d @ redux.js:221
(anonymous) @ middleware.js:26
(anonymous) @ middleware.js:66
dispatch @ redux.js:638
(anonymous) @ utils.js:250
(anonymous) @ proc.js:489
i @ scheduler.js:19
b @ scheduler.js:60
c @ scheduler.js:33
(anonymous) @ channel.js:185
emit @ channel.js:26
(anonymous) @ middleware.js:67
onMessage @ index.js:133
utils.js:225 uncaught at Zg TypeError: Cannot read property 'params' of undefined
    at Function.mapToProps (app://-/static/js/main.d9a1ff8d.chunk.js:1:504127)
    at o (app://-/static/js/2.c06e7841.chunk.js:2:19203)
    at Function.o.mapToProps (app://-/static/js/2.c06e7841.chunk.js:2:19339)
    at o (app://-/static/js/2.c06e7841.chunk.js:2:19203)
    at app://-/static/js/2.c06e7841.chunk.js:2:20569
    at app://-/static/js/2.c06e7841.chunk.js:2:17975
    at Object.useMemo (app://-/static/js/2.c06e7841.chunk.js:2:1114460)
    at t.useMemo (app://-/static/js/2.c06e7841.chunk.js:2:1050982)
    at y (app://-/static/js/2.c06e7841.chunk.js:2:17919)
    at Ji (app://-/static/js/2.c06e7841.chunk.js:2:1109566)
X @ utils.js:225
X @ proc.js:210
(anonymous) @ proc.js:493
i @ scheduler.js:19
b @ scheduler.js:60
c @ scheduler.js:33
(anonymous) @ channel.js:185
emit @ channel.js:26
(anonymous) @ middleware.js:67
onMessage @ index.js:133

Bug report

---

| Debug info | |
| :--- | :--- |
| Version | 3.5.5 |
| Commit Hash | 3fd122fbabbb5f036e1d51f0820d65f944513cd1 |
| Commit Date | 2021-08-27T11:13:16Z |
| Electron | 13.1.9 |
| Chrome | 91.0.4472.164 |
| Node.js | 14.16.0 |
| V8 | 9.1.269.39-electron.0 |
| OS version | Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 |
| OS release | Darwin x64 20.3.0 |
| CPUs | Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz x 12 |
| RAM | 32GB (0.32GB free) |
| App RAM limit | 4095.75Mb (9.08MB used) |

<details>

<summary>Main log</summary>

```vim
[2021-10-10 15:27:55.351] [warn]  Error: ENOENT: no such file or directory, open '/Users/jeremy/Library/Application Support/bfx-report-electron/secret-key'
[2021-10-10 15:27:55.357] [warn]  Error: ENOENT: no such file or directory, unlink '/Users/jeremy/Library/Application Support/bfx-report-electron/secret-key'

```

</details>

<details>

<summary>Worker errors</summary>

```vim
Empty
```

</details>

<details>

<summary>Worker exceptions</summary>

```vim
Empty
```

</details>

---

*The issue was opened from the electron app*

**Comment by ezewer** [comment]
Thanks for reporting, we would send a fix shortly.
