### ISSUE TITLE
[BUG REPORT]

### ISSUE THREAD

**Issue by tiptop100** [bitfinexcom/bfx-report-electron#129]
An error occurred

```vim
WORKER:ERROR [2021-12-19T09:50:53.639Z]     Error: connect ETIMEDOUT 104.16.171.181:443    
  - METHOD_NAME: verifyUser    
  - STATUS_CODE: 500    
  - STATUS_MESSAGE: Internal Server Error        
  - STACK_TRACE RequestError: Error: connect ETIMEDOUT 104.16.171.181:443
    at new RequestError (C:/Users/camc4/Downloads/BitfinexReport-3.6.2-x64-win/resources/app/bfx-reports-framework/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (C:/Users/camc4/Downloads/BitfinexReport-3.6.2-x64-win/resources/app/bfx-reports-framework/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:/Users/camc4/Downloads/BitfinexReport-3.6.2-x64-win/resources/app/bfx-reports-framework/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (C:/Users/camc4/Downloads/BitfinexReport-3.6.2-x64-win/resources/app/bfx-reports-framework/node_modules/bfx-api-node-rest/node_modules/request/request.js:198:22)
    at Request.onRequestError (C:/Users/camc4/Downloads/BitfinexReport-3.6.2-x64-win/resources/app/bfx-reports-framework/node_modules/bfx-api-node-rest/node_modules/request/request.js:820:8)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

```

---

| Debug info | |
| :--- | :--- |
| Version | 3.6.2 |
| Commit Hash | 2f22ef99ea09ab920ec241423232a2bae7b0d722 |
| Commit Date | 2021-12-16T09:29:31Z |
| Electron | 13.6.3 |
| Chrome | 91.0.4472.164 |
| Node.js | 14.16.0 |
| V8 | 9.1.269.39-electron.0 |
| OS version | Windows 10 Home |
| OS release | Windows_NT x64 10.0.19042 |
| CPUs | AMD Ryzen 3 3300U with Radeon Vega Mobile Gfx   x 4 |
| RAM | 5.92GB (0.97GB free) |
| App RAM limit | 2072Mb (8.7MB used) |

<details>

<summary>Main log</summary>

```vim

```

</details>

<details>

<summary>Worker errors</summary>

```vim

```

</details>

<details>

<summary>Worker exceptions</summary>

```vim

```

</details>

---

*The issue was opened from the electron app*

**Comment by ezewer** [comment]
Thanks for reporting, would investigate and come back.

**Comment by ZIMkaRU** [comment]
Thanks for reporting
I try to understand what here was caught and it looks like something does not allow to connect via HTTPS port (not related to the bfx-report tool), so can I ask you the following:
  - try to turn off the firewall and reopen the bfx-report app
  - if you are using any network proxy try to use the app without proxy

**Comment by ezewer** [comment]
@tiptop100 has this solve the issue?

**Comment by tiptop100** [comment]
Sorry for not getting back, yes it did thank you
Regards,
Cam Chippendale
0480 129 179
