### ISSUE TITLE
[BUG REPORT] Loosing internet when sync is happening

### ISSUE THREAD

**Issue by ezewer** [bitfinexcom/bfx-report-electron#131]
When sync is happening if there is a lost of internet connection the following error happens. 
We should consider that a sudden lost of internet is possible. 

```vim
WORKER:ERROR [2022-01-03T01:01:12.784Z]     Error: connect ENETUNREACH 104.16.172.181:443    
  - METHOD_NAME: getFundingLoanHistory    
  - STATUS_CODE: 500    
  - STATUS_MESSAGE: Internal Server Error        
  - STACK_TRACE RequestError: Error: connect ENETUNREACH 104.16.172.181:443
    at new RequestError (/home/ezequiel/Documents/report/BitfinexReport-3.6.2-x64-linux/resources/app/bfx-reports-framework/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/home/ezequiel/Documents/report/BitfinexReport-3.6.2-x64-linux/resources/app/bfx-reports-framework/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/home/ezequiel/Documents/report/BitfinexReport-3.6.2-x64-linux/resources/app/bfx-reports-framework/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/home/ezequiel/Documents/report/BitfinexReport-3.6.2-x64-linux/resources/app/bfx-reports-framework/node_modules/bfx-api-node-rest/node_modules/request/request.js:198:22)
    at Request.onRequestError (/home/ezequiel/Documents/report/BitfinexReport-3.6.2-x64-linux/resources/app/bfx-reports-framework/node_modules/bfx-api-node-rest/node_modules/request/request.js:820:8)
```

---

| Debug info | |
| :--- | :--- |
| Version | 3.6.2 |
| Commit Hash | 2f22ef99ea09ab920ec241423232a2bae7b0d722 |
| Commit Date | 2021-12-16T09:29:31Z |
| Electron | 13.6.3 |
| Chrome | 91.0.4472.164 |
| Node.js | 14.16.0 |
| V8 | 9.1.269.39-electron.0 |
| OS version | Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 |
| OS release | Linux x64 5.4.0-91-generic |
| CPUs | Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz x 8 |
| RAM | 15.53GB (0.41GB free) |
| App RAM limit | 4095.75Mb (8.66MB used) |

<details>

<summary>Main log</summary>

```vim
    at self.callback (/home/ezequiel/Documents/report/BitfinexReport-3.6.2-x64-linux/resources/app/bfx-reports-framework/node_modules/bfx-api-node-rest/node_modules/request/request.js:
    at Request.onRequestError (/home/ezequiel/Documents/report/BitfinexReport-3.6.2-x64-linux/resources/app/bfx-reports-framework/node_modules/bfx-api-node-rest/node_modules/request/request.js:820:8)
[2022-01-03 12:01:12.853] [error] WORKER:ERROR [2022-01-03T01:01:12.799Z] PROGRESS:SYNC: RequestError: Error: connect ENETUNREACH 104.16.172.181:443
    at new RequestError (/home/ezequiel/Documents/report/BitfinexReport-3.6.2-x64-linux/resources/app/bfx-reports-framework/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/home/ezequiel/Documents/report/BitfinexReport-3.6.2-x64-linux/resources/app/bfx-reports-framework/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/home/ezequiel/Documents/report/BitfinexReport-3.6.2-x64-linux/resources/app/bfx-reports-framework/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/home/ezequiel/Documents/report/BitfinexReport-3.6.2-x64-linux/resources/app/bfx-reports-framework/node_modules/bfx-api-node-rest/node_modules/request/request.js:198:22)
    at Request.onRequestError (/home/ezequiel/Documents/report/BitfinexReport-3.6.2-x64-linux/resources/app/bfx-reports-framework/node_modules/bfx-api-node-rest/node_modules/request/request.js:820:8)

```

</details>

<details>

<summary>Worker errors</summary>

```vim
    at processTicksAndRejections (internal/pr
WORKER:ERROR [2022-01-03T01:01:12.799Z] PROGRESS:SYNC: RequestError: Error: connect ENETUNREACH 104.16.172.181:443
    at new RequestError (/home/ezequiel/Documents/report/BitfinexReport-3.6.2-x64-linux/resources/app/bfx-reports-framework/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/home/ezequiel/Documents/report/BitfinexReport-3.6.2-x64-linux/resources/app/bfx-reports-framework/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/home/ezequiel/Documents/report/BitfinexReport-3.6.2-x64-linux/resources/app/bfx-reports-framework/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/home/ezequiel/Documents/report/BitfinexReport-3.6.2-x64-linux/resources/app/bfx-reports-framework/node_modules/bfx-api-node-rest/node_modules/request/request.js:198:22)
    at Request.emit (events.js:315:20)
    at Request.onRequestError (/home/ezequiel/Documents/report/BitfinexReport-3.6.2-x64-linux/resources/app/bfx-reports-framework/node_modules/bfx-api-node-rest/node_modules/request/request.js:820:8)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

```

</details>

<details>

<summary>Worker exceptions</summary>

```vim
    at /home/ezequiel/Documents/report/BitfinexReport-3.5.0-x64-linux/resources/app/bfx-reports-framework/node_modules/async
    at /home/ezequiel/Documents/report/BitfinexReport-3.5.0-x64-linux/resources/app/bfx-reports-framework/node_modules/async/dist/async.js:2953:17
    at /home/ezequiel/Documents/report/BitfinexReport-3.5.0-x64-linux/resources/app/bfx-reports-framework/node_modules/async/dist/async.js:2955:19
    at wrapper (/home/ezequiel/Documents/report/BitfinexReport-3.5.0-x64-linux/resources/app/bfx-reports-framework/node_modules/async/dist/async.js:268:20)
    at replenish (/home/ezequiel/Documents/report/BitfinexReport-3.5.0-x64-linux/resources/app/bfx-reports-framework/node_modules/async/dist/async.js:435:29)
    at iterateeCallback (/home/ezequiel/Documents/report/BitfinexReport-3.5.0-x64-linux/resources/app/bfx-reports-framework/node_modules/async/dist/async.js:424:21)
    at /home/ezequiel/Documents/report/BitfinexReport-3.5.0-x64-linux/resources/app/bfx-reports-framework/node_modules/async/dist/async.js:321:20
    at /home/ezequiel/Documents/report/BitfinexReport-3.5.0-x64-linux/resources/app/bfx-reports-framework/node_modules/async/dist/async.js:2953:17
    at /home/ezequiel/Documents/report/BitfinexReport-3.5.0-x64-linux/resources/app/bfx-reports-framework/node_modules/async/dist/async.js:2955:19
    at wrapper (/home/ezequiel/Documents/report/BitfinexReport-3.5.0-x64-linux/resources/app/bfx-reports-framework/node_modules/async/dist/async.js:268:20)

```

</details>

---

*The issue was opened from the electron app*

**Comment by ZIMkaRU** [comment]
sure, thanks, would take into consideration that error
