### ISSUE TITLE
[BUG REPORT] Reporting the error does not allow to follow up, forcing to close the app

### ISSUE THREAD

**Issue by ezewer** [bitfinexcom/bfx-report-electron#149]
An error occurred

```vim
WORKER:ERROR [2022-05-13T06:50:09.323Z]     Error: ETIMEDOUT    
  - METHOD_NAME: verifyUser    
  - STATUS_CODE: 500    
  - STATUS_MESSAGE: Internal Server Error        
  - STACK_TRACE RequestError: Error: ETIMEDOUT
    at new RequestError (/home/ezequiel/Documents/report/BitfinexReport-3.7.1-x64-linux/resources/app/bfx-reports-framework/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/home/ezequiel/Documents/report/BitfinexReport-3.7.1-x64-linux/resources/app/bfx-reports-framework/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/home/ezequiel/Documents/report/BitfinexReport-3.7.1-x64-linux/resources/app/bfx-reports-framework/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/home/ezequiel/Documents/report/BitfinexReport-3.7.1-x64-linux/resources/app/bfx-reports-framework/node_modules/bfx-api-node-rest/node_modules/request/request.js:198:22)
    at Timeout._onTimeout (/home/ezequiel/Documents/report/BitfinexReport-3.7.1-x64-linux/resources/app/bfx-reports-framework/node_modules/bfx-api-node-rest/node_modules/request/request.js:764:12)
```

---

| Debug info | |
| :--- | :--- |
| Version | 3.7.1 |
| Commit Hash | 6e2c58d16fb928dda694f5b4c172bd3765909b1d |
| Commit Date | 2022-05-03T01:43:11Z |
| Electron | 13.6.9 |
| Chrome | 91.0.4472.164 |
| Node.js | 14.16.0 |
| V8 | 9.1.269.40-electron.0 |
| OS version | Ubuntu SMP Thu Apr 14 19:46:19 UTC 2022 |
| OS release | Linux x64 5.4.0-110-generic |
| CPUs | Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz x 8 |
| RAM | 15.52GB (0.54GB free) |
| App RAM limit | 4095.75Mb (9.39MB used) |

<details>

<summary>Main log</summary>

```vim
    at self.callback (/home/ezequiel/Documents/report/BitfinexReport-3.7.1-x64-linux/resources/app/bfx-reports
    at Timeout._onTimeout (/home/ezequiel/Documents/report/BitfinexReport-3.7.1-x64-linux/resources/app/bfx-reports-framework/node_modules/bfx-api-node-rest/node_modules/request/request.js:764:12)
[2022-05-13 16:50:09.330] [error] WORKER:ERROR [2022-05-13T06:50:09.323Z]     Error: ETIMEDOUT    
  - METHOD_NAME: verifyUser    
  - STATUS_CODE: 500    
  - STATUS_MESSAGE: Internal Server Error        
  - STACK_TRACE RequestError: Error: ETIMEDOUT
    at new RequestError (/home/ezequiel/Documents/report/BitfinexReport-3.7.1-x64-linux/resources/app/bfx-reports-framework/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/home/ezequiel/Documents/report/BitfinexReport-3.7.1-x64-linux/resources/app/bfx-reports-framework/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/home/ezequiel/Documents/report/BitfinexReport-3.7.1-x64-linux/resources/app/bfx-reports-framework/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/home/ezequiel/Documents/report/BitfinexReport-3.7.1-x64-linux/resources/app/bfx-reports-framework/node_modules/bfx-api-node-rest/node_modules/request/request.js:198:22)
    at Timeout._onTimeout (/home/ezequiel/Documents/report/BitfinexReport-3.7.1-x64-linux/resources/app/bfx-reports-framework/node_modules/bfx-api-node-rest/node_modules/request/request.js:764:12)

```

</details>

<details>

<summary>Worker errors</summary>

```vim
    at Timeout._onTimeout (/home/ezequiel/Documents/report/BitfinexReport-3.7.1-x64-linux/resources/app/bfx-
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
WORKER:ERROR [2022-05-13T06:50:09.323Z]     Error: ETIMEDOUT    
  - METHOD_NAME: verifyUser    
  - STATUS_CODE: 500    
  - STATUS_MESSAGE: Internal Server Error        
  - STACK_TRACE RequestError: Error: ETIMEDOUT
    at new RequestError (/home/ezequiel/Documents/report/BitfinexReport-3.7.1-x64-linux/resources/app/bfx-reports-framework/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/home/ezequiel/Documents/report/BitfinexReport-3.7.1-x64-linux/resources/app/bfx-reports-framework/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/home/ezequiel/Documents/report/BitfinexReport-3.7.1-x64-linux/resources/app/bfx-reports-framework/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/home/ezequiel/Documents/report/BitfinexReport-3.7.1-x64-linux/resources/app/bfx-reports-framework/node_modules/bfx-api-node-rest/node_modules/request/request.js:198:22)
    at Request.emit (events.js:315:20)
    at Timeout._onTimeout (/home/ezequiel/Documents/report/BitfinexReport-3.7.1-x64-linux/resources/app/bfx-reports-framework/node_modules/bfx-api-node-rest/node_modules/request/request.js:764:12)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)

```

</details>

<details>

<summary>Worker exceptions</summary>

```vim
  
    at /home/ezequiel/Documents/report/BitfinexReport-3.5.0-x64-linux/resources/app/bfx-reports-framework/node_modules/async/dist/async.js:321:20
    at /home/ezequiel/Documents/report/BitfinexReport-3.5.0-x64-linux/resources/app/bfx-reports-framework/node_modules/async/dist/async.js:2953:17
    at /home/ezequiel/Documents/report/BitfinexReport-3.5.0-x64-linux/resources/app/bfx-reports-framework/node_modules/async/dist/async.js:2955:19
    at wrapper (/home/ezequiel/Documents/report/BitfinexReport-3.5.0-x64-linux/resources/app/bfx-reports-framework/node_modules/async/dist/async.js:268:20)
    at replenish (/home/ezequiel/Documents/report/BitfinexReport-3.5.0-x64-linux/resources/app/bfx-reports-framework/node_modules/async/dist/async.js:435:29)
    at iterateeCallback (/home/ezequiel/Documents/report/BitfinexReport-3.5.0-x64-linux/resources/app/bfx-reports-framework/node_modules/async/dist/async.js:424:21)
    at /home/ezequiel/Documents/report/BitfinexReport-3.5.0-x64-linux/resources/app/bfx-reports-framework/node_modules/async/dist/async.js:321:20
    at /home/ezequiel/Documents/report/BitfinexReport-3.5.0-x64-linux/resources/app/bfx-reports-framework/node_modules/async/dist/async.js:2953:17
    at /home/ezequiel/Documents/report/BitfinexReport-3.5.0-x64-linux/resources/app/bfx-reports-framework/node_modules/async/dist/async.js:2955:19
    at wrapper (/home/ezequiel/Documents/report/BitfinexReport-3.5.0-x64-linux/resources/app/bfx-reports-framework/node_modules/async/dist/async.js:268:20)

```

</details>

---

*The issue was opened from the electron app*

**Comment by ezewer** [comment]
Fixed
