### ISSUE TITLE
[BUG REPORT] version 3.7.3 issue with unique constraint

### ISSUE THREAD

**Issue by ezewer** [bitfinexcom/bfx-report-electron#156]
An error occurred

```vim
WORKER:ERROR [2022-07-12T09:49:49.935Z]     UNIQUE constraint failed: users.email, users.username    
  - METHOD_NAME: createSubAccount    
  - STATUS_CODE: 500    
  - STATUS_MESSAGE: Internal Server Error        
  - STACK_TRACE SqliteError: UNIQUE constraint failed: users.email, users.username
    at Object.module.exports [as RUN] (/tmp/.mount_BitfinBxwiEJ/resources/app/bfx-reports-framework/node_modules/bfx-facs-db-better-sqlite/worker/db-worker-actions/action-run.js:8:11)
    at module.exports (/tmp/.mount_BitfinBxwiEJ/resources/app/bfx-reports-framework/node_modules/bfx-facs-db-better-sqlite/worker/db-worker-actions/index.js:16:31)
    at module.exports (/tmp/.mount_BitfinBxwiEJ/resources/app/bfx-reports-framework/workers/loc.api/sync/dao/sqlite-worker/db-worker-actions/index.js:21:10)
    at BetterSqliteDAO.query (/tmp/.mount_BitfinBxwiEJ/resources/app/bfx-reports-framework/workers/loc.api/sync/dao/dao.better.sqlite.js:108:14)
    at BetterSqliteDAO.insertElemToDb (/tmp/.mount_BitfinBxwiEJ/resources/app/bfx-reports-framework/workers/loc.api/sync/dao/dao.better.sqlite.js:539:23)
    at Authenticator.createUser (/tmp/.mount_BitfinBxwiEJ/resources/app/bfx-reports-framework/workers/loc.api/sync/authenticator/index.js:754:48)
    at Authenticator.signUp (/tmp/.mount_BitfinBxwiEJ/resources/app/bfx-reports-framework/workers/loc.api/sync/authenticator/index.js:141:29)
    at async dao.executeQueriesInTrans.withoutWorkerThreads (/tmp/.mount_BitfinBxwiEJ/resources/app/bfx-reports-framework/workers/loc.api/sync/sub.account/index.js:105:30)
    at async _beginTrans.beforeTransFn.beforeTransFn (/tmp/.mount_BitfinBxwiEJ/resources/app/bfx-reports-framework/workers/loc.api/sync/dao/dao.better.sqlite.js:449:22)
    at async BetterSqliteDAO._proccesTrans (/tmp/.mount_BitfinBxwiEJ/resources/app/bfx-reports-framework/workers/loc.api/sync/dao/dao.better.sqlite.js:133:19)
    at async module.exports (/tmp/.mount_BitfinBxwiEJ/resources/app/bfx-reports-framework/workers/loc.api/sync/dao/helpers/manage-transaction/index.js:24:17)
```

---

| Debug info | |
| :--- | :--- |
| Version | 3.7.3 |
| Commit Hash | a06970096146a51ca3b86499930319a406fc49b6 |
| Commit Date | 2022-07-08T07:52:07Z |
| Electron | 13.6.9 |
| Chrome | 91.0.4472.164 |
| Node.js | 14.16.0 |
| V8 | 9.1.269.40-electron.0 |
| OS version | Ubuntu SMP Wed Jun 15 13:33:07 UTC 2022 |
| OS release | Linux x64 5.4.0-121-generic |
| CPUs | Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz x 8 |
| RAM | 15.52GB (1.01GB free) |
| App RAM limit | 4095.75Mb (10.01MB used) |

<details>

<summary>Main log</summary>

```vim
    at BetterSqliteDAO.query (/tmp/.mount_BitfinBxwiEJ/resources/app/bfx-reports-framework/workers/loc.api/sync/dao/dao.better.sqlite.js:1
    at BetterSqliteDAO.insertElemToDb (/tmp/.mount_BitfinBxwiEJ/resources/app/bfx-reports-framework/workers/loc.api/sync/dao/dao.better.sqlite.js:539:23)
    at Authenticator.createUser (/tmp/.mount_BitfinBxwiEJ/resources/app/bfx-reports-framework/workers/loc.api/sync/authenticator/index.js:754:48)
    at Authenticator.signUp (/tmp/.mount_BitfinBxwiEJ/resources/app/bfx-reports-framework/workers/loc.api/sync/authenticator/index.js:141:29)
    at async dao.executeQueriesInTrans.withoutWorkerThreads (/tmp/.mount_BitfinBxwiEJ/resources/app/bfx-reports-framework/workers/loc.api/sync/sub.account/index.js:105:30)
    at async _beginTrans.beforeTransFn.beforeTransFn (/tmp/.mount_BitfinBxwiEJ/resources/app/bfx-reports-framework/workers/loc.api/sync/dao/dao.better.sqlite.js:449:22)
    at async BetterSqliteDAO._proccesTrans (/tmp/.mount_BitfinBxwiEJ/resources/app/bfx-reports-framework/workers/loc.api/sync/dao/dao.better.sqlite.js:133:19)
    at async module.exports (/tmp/.mount_BitfinBxwiEJ/resources/app/bfx-reports-framework/workers/loc.api/sync/dao/helpers/manage-transaction/index.js:24:17)

```

</details>

<details>

<summary>Worker errors</summary>

```vim
    at BetterSqliteDAO.query (/tmp/.mount_BitfinBxwiEJ/resources/app/bfx-reports-framework/workers/loc.api/sync/dao/dao.better.sqlite.js:1
    at BetterSqliteDAO.insertElemToDb (/tmp/.mount_BitfinBxwiEJ/resources/app/bfx-reports-framework/workers/loc.api/sync/dao/dao.better.sqlite.js:539:23)
    at Authenticator.createUser (/tmp/.mount_BitfinBxwiEJ/resources/app/bfx-reports-framework/workers/loc.api/sync/authenticator/index.js:754:48)
    at Authenticator.signUp (/tmp/.mount_BitfinBxwiEJ/resources/app/bfx-reports-framework/workers/loc.api/sync/authenticator/index.js:141:29)
    at async dao.executeQueriesInTrans.withoutWorkerThreads (/tmp/.mount_BitfinBxwiEJ/resources/app/bfx-reports-framework/workers/loc.api/sync/sub.account/index.js:105:30)
    at async _beginTrans.beforeTransFn.beforeTransFn (/tmp/.mount_BitfinBxwiEJ/resources/app/bfx-reports-framework/workers/loc.api/sync/dao/dao.better.sqlite.js:449:22)
    at async BetterSqliteDAO._proccesTrans (/tmp/.mount_BitfinBxwiEJ/resources/app/bfx-reports-framework/workers/loc.api/sync/dao/dao.better.sqlite.js:133:19)
    at async module.exports (/tmp/.mount_BitfinBxwiEJ/resources/app/bfx-reports-framework/workers/loc.api/sync/dao/helpers/manage-transaction/index.js:24:17)

```

</details>

<details>

<summary>Worker exceptions</summary>

```vim
    at /home/eze
    at /home/ezequiel/Documents/report/BitfinexReport-3.5.0-x64-linux/resources/app/bfx-reports-framework/node_modules/async/dist/async.js:2955:19
    at wrapper (/home/ezequiel/Documents/report/BitfinexReport-3.5.0-x64-linux/resources/app/bfx-reports-framework/node_modules/async/dist/async.js:268:20)
    at replenish (/home/ezequiel/Documents/report/BitfinexReport-3.5.0-x64-linux/resources/app/bfx-reports-framework/node_modules/async/dist/async.js:435:29)
    at iterateeCallback (/home/ezequiel/Documents/report/BitfinexReport-3.5.0-x64-linux/resources/app/bfx-reports-framework/node_modules/async/dist/async.js:424:21)
    at /home/ezequiel/Documents/report/BitfinexReport-3.5.0-x64-linux/resources/app/bfx-reports-framework/node_modules/async/dist/async.js:321:20
    at /home/ezequiel/Documents/report/BitfinexReport-3.5.0-x64-linux/resources/app/bfx-reports-framework/node_modules/async/dist/async.js:2953:17
    at /home/ezequiel/Documents/report/BitfinexReport-3.5.0-x64-linux/resources/app/bfx-reports-framework/node_modules/async/dist/async.js:2955:19
    at wrapper (/home/ezequiel/Documents/report/BitfinexReport-3.5.0-x64-linux/resources/app/bfx-reports-framework/node_modules/async/dist/async.js:268:20)

```

</details>

---

*The issue was opened from the electron app*

**Comment by ezewer** [comment]
Solved
