### ISSUE TITLE
[BUG REPORT] - Sync after updating to v 4.0.0

### ISSUE THREAD

**Issue by BeastOfBodmin** [bitfinexcom/bfx-report-electron#176]
An error occurred

```vim
WORKER:ERROR [2023-01-13T14:33:40.048Z]     Error: ETIMEDOUT    
  - METHOD_NAME: getFundingOfferHistory    
  - STATUS_CODE: 500    
  - STATUS_MESSAGE: Internal Server Error        
  - STACK_TRACE RequestError: Error: ETIMEDOUT
    at new RequestError (/Applications/Bitfinex Report.app/Contents/Resources/app/bfx-reports-framework/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Applications/Bitfinex Report.app/Contents/Resources/app/bfx-reports-framework/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Applications/Bitfinex Report.app/Contents/Resources/app/bfx-reports-framework/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Applications/Bitfinex Report.app/Contents/Resources/app/bfx-reports-framework/node_modules/bfx-api-node-rest/node_modules/request/request.js:198:22)
    at Timeout._onTimeout (/Applications/Bitfinex Report.app/Contents/Resources/app/bfx-reports-framework/node_modules/bfx-api-node-rest/node_modules/request/request.js:764:12)
```

---

| Debug info | |
| :--- | :--- |
| Version | 4.0.0 |
| Commit Hash | af2d6b6590c56d659a79d25e137d59bc4a81fe83 |
| Commit Date | 2022-12-14T14:14:17Z |
| Electron | 13.6.9 |
| Chrome | 91.0.4472.164 |
| Node.js | 14.16.0 |
| V8 | 9.1.269.40-electron.0 |
| OS version | Darwin Kernel Version 22.2.0: Fri Nov 11 02:08:47 PST 2022; root:xnu-8792.61.2~4/RELEASE_X86_64 |
| OS release | Darwin x64 22.2.0 |
| CPUs | Intel(R) Core(TM) i7-4771 CPU @ 3.50GHz x 8 |
| RAM | 28GB (0.13GB free) |
| App RAM limit | 4095.75Mb (8.97MB used) |

<details>

<summary>Main log</summary>

```vim
[2022-11-21 21:22:45.861] [error] Error: ne
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:7068)
[2022-11-22 09:22:44.464] [error] (node:35119) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 closed listeners added to [BrowserWindow]. Use emitter.setMaxListeners() to increase limit
    at _fireAlert (/Applications/Bitfinex Report.app/Contents/Resources/app/src/error-manager/show-modal-dialog.js:74:7)
    at module.exports (/Applications/Bitfinex Report.app/Contents/Resources/app/src/error-manager/show-modal-dialog.js:172:15)
    at manageNewGithubIssue (/Applications/Bitfinex Report.app/Contents/Resources/app/src/error-manager/index.js:141:15)
    at async _manageErrorLogLevel (/Applications/Bitfinex Report.app/Contents/Resources/app/src/error-manager/index.js:51:24)
[2023-01-13 14:29:01.877] [warn]  sysctl shell command to check for macOS Rosetta environment failed: Error: Command failed: sysctl sysctl.proc_translated
sysctl: unknown oid 'sysctl.proc_translated'
[2023-01-13 15:29:10.194] [warn]  sysctl shell command to check for macOS Rosetta environment failed: Error: Command failed: sysctl sysctl.proc_translated
sysctl: unknown oid 'sysctl.proc_translated'
[2023-01-13 15:33:40.050] [error] WORKER:ERROR [2023-01-13T14:33:40.048Z]     Error: ETIMEDOUT    
  - METHOD_NAME: getFundingOfferHistory    
  - STATUS_CODE: 500    
  - STATUS_MESSAGE: Internal Server Error        
  - STACK_TRACE RequestError: Error: ETIMEDOUT
    at new RequestError (/Applications/Bitfinex Report.app/Contents/Resources/app/bfx-reports-framework/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Applications/Bitfinex Report.app/Contents/Resources/app/bfx-reports-framework/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Applications/Bitfinex Report.app/Contents/Resources/app/bfx-reports-framework/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Applications/Bitfinex Report.app/Contents/Resources/app/bfx-reports-framework/node_modules/bfx-api-node-rest/node_modules/request/request.js:198:22)
    at Timeout._onTimeout (/Applications/Bitfinex Report.app/Contents/Resources/app/bfx-reports-framework/node_modules/bfx-api-node-rest/node_modules/request/request.js:764:12)

```

</details>

<details>

<summary>Worker errors</summary>

```vim
    at new RequestError (/Applications/Bitfinex Report.app/
    at Request.plumbing.callback (/Applications/Bitfinex Report.app/Contents/Resources/app/bfx-reports-framework/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Applications/Bitfinex Report.app/Contents/Resources/app/bfx-reports-framework/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Applications/Bitfinex Report.app/Contents/Resources/app/bfx-reports-framework/node_modules/bfx-api-node-rest/node_modules/request/request.js:198:22)
    at Request.emit (events.js:315:20)
    at Request.onRequestError (/Applications/Bitfinex Report.app/Contents/Resources/app/bfx-reports-framework/node_modules/bfx-api-node-rest/node_modules/request/request.js:820:8)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
WORKER:ERROR [2023-01-13T14:33:40.048Z]     Error: ETIMEDOUT    
  - METHOD_NAME: getFundingOfferHistory    
  - STATUS_CODE: 500    
  - STATUS_MESSAGE: Internal Server Error        
  - STACK_TRACE RequestError: Error: ETIMEDOUT
    at new RequestError (/Applications/Bitfinex Report.app/Contents/Resources/app/bfx-reports-framework/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Applications/Bitfinex Report.app/Contents/Resources/app/bfx-reports-framework/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Applications/Bitfinex Report.app/Contents/Resources/app/bfx-reports-framework/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Applications/Bitfinex Report.app/Contents/Resources/app/bfx-reports-framework/node_modules/bfx-api-node-rest/node_modules/request/request.js:198:22)
    at Request.emit (events.js:315:20)
    at Timeout._onTimeout (/Applications/Bitfinex Report.app/Contents/Resources/app/bfx-reports-framework/node_modules/bfx-api-node-rest/node_modules/request/request.js:764:12)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)

```

</details>

<details>

<summary>Worker exceptions</summary>

```vim
Empty
```

</details>

---

*The issue was opened from the electron app*

**Comment by ZIMkaRU** [comment]
thanks for the report, it should be improved in the next release, fix https://github.com/bitfinexcom/bfx-report/pull/278

**Comment by ezewer** [comment]
Close as this has been solved
