### ISSUE TITLE
LogIn Issue from China Mainland! Need a network setting for Socks5 proxy!

### ISSUE THREAD

**Issue by Ken-n** [bitfinexcom/bfx-report-electron#197]
An error occurred

```vim
WORKER:ERROR [2023-04-27T05:23:03.793Z]     Error: ETIMEDOUT    
  - METHOD_NAME: signUp    
  - STATUS_CODE: 500    
  - STATUS_MESSAGE: Internal Server Error        
  - STACK_TRACE RequestError: Error: ETIMEDOUT
    at new RequestError (/Applications/Bitfinex Report.app/Contents/Resources/app/bfx-reports-framework/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Applications/Bitfinex Report.app/Contents/Resources/app/bfx-reports-framework/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Applications/Bitfinex Report.app/Contents/Resources/app/bfx-reports-framework/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Applications/Bitfinex Report.app/Contents/Resources/app/bfx-reports-framework/node_modules/bfx-api-node-rest/node_modules/request/request.js:198:22)
    at Timeout._onTimeout (/Applications/Bitfinex Report.app/Contents/Resources/app/bfx-reports-framework/node_modules/bfx-api-node-rest/node_modules/request/request.js:764:12)
```

---

| Debug info | |
| :--- | :--- |
| Version | 4.5.1 |
| Commit Hash | 721acbda1a5e7b4930571918aeecdff2523ba15d |
| Commit Date | 2023-04-26T10:39:39Z |
| Electron | 13.6.9 |
| Chrome | 91.0.4472.164 |
| Node.js | 14.16.0 |
| V8 | 9.1.269.40-electron.0 |
| OS version | Darwin Kernel Version 18.7.0: Tue Jun 22 19:37:08 PDT 2021; root:xnu-4903.278.70~1/RELEASE_X86_64 |
| OS release | Darwin x64 18.7.0 |
| CPUs | Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz x 4 |
| RAM | 8GB (0.05GB free) |
| App RAM limit | 2072Mb (9.65MB used) |

<details>

<summary>Main log</summary>

```vim
    at Timeout._onTimeout (/Applications/Bitfinex Report.app/Contents/Resources/app/bfx-reports-framework/node_modules/bfx-api-node-rest/node_modules/
[2023-04-27 12:28:10.863] [error] WORKER:ERROR [2023-04-27T04:28:10.862Z]     Error: ETIMEDOUT    
  - METHOD_NAME: loginToBFX    
  - STATUS_CODE: 500    
  - STATUS_MESSAGE: Internal Server Error        
  - STACK_TRACE RequestError: Error: ETIMEDOUT
    at new RequestError (/Applications/Bitfinex Report.app/Contents/Resources/app/bfx-reports-framework/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Applications/Bitfinex Report.app/Contents/Resources/app/bfx-reports-framework/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Applications/Bitfinex Report.app/Contents/Resources/app/bfx-reports-framework/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Applications/Bitfinex Report.app/Contents/Resources/app/bfx-reports-framework/node_modules/bfx-api-node-rest/node_modules/request/request.js:198:22)
    at Timeout._onTimeout (/Applications/Bitfinex Report.app/Contents/Resources/app/bfx-reports-framework/node_modules/bfx-api-node-rest/node_modules/request/request.js:764:12)
[2023-04-27 13:23:03.811] [error] WORKER:ERROR [2023-04-27T05:23:03.793Z]     Error: ETIMEDOUT    
  - METHOD_NAME: signUp    
  - STATUS_CODE: 500    
  - STATUS_MESSAGE: Internal Server Error        
  - STACK_TRACE RequestError: Error: ETIMEDOUT
    at new RequestError (/Applications/Bitfinex Report.app/Contents/Resources/app/bfx-reports-framework/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Applications/Bitfinex Report.app/Contents/Resources/app/bfx-reports-framework/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Applications/Bitfinex Report.app/Contents/Resources/app/bfx-reports-framework/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Applications/Bitfinex Report.app/Contents/Resources/app/bfx-reports-framework/node_modules/bfx-api-node-rest/node_modules/request/request.js:198:22)
    at Timeout._onTimeout (/Applications/Bitfinex Report.app/Contents/Resources/app/bfx-reports-framework/node_modules/bfx-api-node-rest/node_modules/request/request.js:764:12)

```

</details>

<details>

<summary>Worker errors</summary>

```vim
WORKER:ERRO
  - METHOD_NAME: loginToBFX    
  - STATUS_CODE: 500    
  - STATUS_MESSAGE: Internal Server Error        
  - STACK_TRACE RequestError: Error: ETIMEDOUT
    at new RequestError (/Applications/Bitfinex Report.app/Contents/Resources/app/bfx-reports-framework/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Applications/Bitfinex Report.app/Contents/Resources/app/bfx-reports-framework/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Applications/Bitfinex Report.app/Contents/Resources/app/bfx-reports-framework/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Applications/Bitfinex Report.app/Contents/Resources/app/bfx-reports-framework/node_modules/bfx-api-node-rest/node_modules/request/request.js:198:22)
    at Request.emit (events.js:315:20)
    at Timeout._onTimeout (/Applications/Bitfinex Report.app/Contents/Resources/app/bfx-reports-framework/node_modules/bfx-api-node-rest/node_modules/request/request.js:764:12)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
WORKER:ERROR [2023-04-27T05:23:03.793Z]     Error: ETIMEDOUT    
  - METHOD_NAME: signUp    
  - STATUS_CODE: 500    
  - STATUS_MESSAGE: Internal Server Error        
  - STACK_TRACE RequestError: Error: ETIMEDOUT
    at new RequestError (/Applications/Bitfinex Report.app/Contents/Resources/app/bfx-reports-framework/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/Applications/Bitfinex Report.app/Contents/Resources/app/bfx-reports-framework/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/Applications/Bitfinex Report.app/Contents/Resources/app/bfx-reports-framework/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/Applications/Bitfinex Report.app/Contents/Resources/app/bfx-reports-framework/node_modules/bfx-api-node-rest/node_modules/request/request.js:198:22)
    at Request.emit (events.js:315:20)
    at Timeout._onTimeout (/Applications/Bitfinex Report.app/Contents/Resources/app/bfx-reports-framework/node_modules/bfx-api-node-rest/node_modules/request/request.js:764:12)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)

```

</details>

<details>

<summary>Worker exceptions</summary>

```vim
Empty
```

</details>

---

*The issue was opened from the electron app*

**Comment by ezewer** [comment]
Hi @Ken-n do you experience this only when using the report tool or also when accessing bitfinex.com ?

**Comment by Ken-n** [comment]
> 



> Hi @Ken-n do you experience this only when using the report tool or also when accessing bitfinex.com ?

Only when using the report tool, because I access bitfinex.com on my browser which allows me to set a proxy.

**Comment by Ken-n** [comment]
> 



> Hi @Ken-n do you experience this only when using the report tool or also when accessing bitfinex.com ?

Only when using the report tool, because I access bitfinex.com on my browser which allows me to set a proxy.

**Comment by ezewer** [comment]
@Ken-n thanks for reporting, checking!

**Comment by ezewer** [comment]
Hi @Ken-n has this been solved?

**Comment by krm35** [comment]
You can use electron proxy arguments in the command line:

./BitfinexReport-4.16.0-x64-linux.AppImage --proxy-server=IP:PORT --proxy-bypass-list=<-loopback>
