### ISSUE TITLE
[BUG REPORT]

### ISSUE THREAD

**Issue by shah-sami** [bitfinexcom/bfx-report-electron#215]
An error occurred

```vim
(node:14064) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 closed listeners added to [BrowserWindow]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:601:17)
    at BrowserWindow.addListener (node:events:619:10)
    at BrowserWindow.once (node:events:663:8)
    at _fireToast (C:/Users/SS3/AppData/Local/Programs/bfx-report-electron/resources/app/src/auto-updater/index.js:95:7)
    at NsisUpdater.<anonymous> (C:/Users/SS3/AppData/Local/Programs/bfx-report-electron/resources/app/src/auto-updater/index.js:432:31)
    at NsisUpdater.emit (node:events:527:28)
    at NsisUpdater.dispatchUpdateDownloaded (C:/Users/SS3/AppData/Local/Programs/bfx-report-electron/resources/app/node_modules/electron-updater/out/AppUpdater.js:404:14)
    at Object.done (C:/Users/SS3/AppData/Local/Programs/bfx-report-electron/resources/app/node_modules/electron-updater/out/BaseUpdater.js:30:22)
    at done (C:/Users/SS3/AppData/Local/Programs/bfx-report-electron/resources/app/node_modules/electron-updater/out/AppUpdater.js:516:31)
```

---

| Debug info | |
| :--- | :--- |
| Version | 4.8.0 |
| Commit Hash | bab409923e47070ec3bfcc579f820e692b31439d |
| Commit Date | 2023-06-21T12:34:00Z |
| Electron | 21.3.3 |
| Chrome | 106.0.5249.199 |
| Node.js | 16.16.0 |
| V8 | 10.6.194.26-electron.0 |
| OS version | Windows 10 Pro |
| OS release | Windows_NT x64 10.0.19045 |
| CPUs | Intel(R) Core(TM) i9-10980XE CPU @ 3.00GHz x 36 |
| RAM | 255.72GB (227.74GB free) |
| App RAM limit | 4095.75Mb (12.89MB used) |
| Is BFX API Staging used | No |

<details>

<summary>Main log</summary>

```vim

```

</details>

<details>

<summary>Worker errors</summary>

```vim

```

</details>

<details>

<summary>Worker exceptions</summary>

```vim

```

</details>

---

*The issue was opened from the electron app*

**Comment by ZIMkaRU** [comment]
Hi)
thanks for the report
It seems that the problem occurred during auto-update
We'll try to fix the issue for the next release
