### ISSUE TITLE
[BUG REPORT] SqliteError

### ISSUE THREAD

**Issue by ezewer** [bitfinexcom/bfx-report-electron#217]
An error occurred

```vim
WORKER:ERROR [2023-06-23T09:49:06.691Z] PROGRESS:SYNC: SqliteError: table temp_s29_currencies has no column named symbol
    at Database.prepare (/tmp/.mount_BitfinQm4x2w/resources/app/bfx-reports-framework/node_modules/better-sqlite3/lib/methods/wrappers.js:5:21)
    at module.exports [as RUN] (/tmp/.mount_BitfinQm4x2w/resources/app/bfx-reports-framework/node_modules/bfx-facs-db-better-sqlite/worker/db-worker-actions/action-run.js:4:18)
    at module.exports (/tmp/.mount_BitfinQm4x2w/resources/app/bfx-reports-framework/node_modules/bfx-facs-db-better-sqlite/worker/db-worker-actions/index.js:16:31)
    at module.exports (/tmp/.mount_BitfinQm4x2w/resources/app/bfx-reports-framework/workers/loc.api/sync/dao/sqlite-worker/db-worker-actions/index.js:21:10)
    at BetterSqliteDAO.query (/tmp/.mount_BitfinQm4x2w/resources/app/bfx-reports-framework/workers/loc.api/sync/dao/dao.better.sqlite.js:120:20)
    at /tmp/.mount_BitfinQm4x2w/resources/app/bfx-reports-framework/workers/loc.api/sync/dao/dao.better.sqlite.js:840:20
    at async BetterSqliteDAO._proccesTrans (/tmp/.mount_BitfinQm4x2w/resources/app/bfx-reports-framework/workers/loc.api/sync/dao/dao.better.sqlite.js:162:19)
    at async /tmp/.mount_BitfinQm4x2w/resources/app/bfx-reports-framework/workers/loc.api/sync/dao/helpers/manage-transaction/index.js:14:12
    at async module.exports (/tmp/.mount_BitfinQm4x2w/resources/app/bfx-reports-framework/workers/loc.api/sync/dao/helpers/manage-transaction/index.js:20:17)
    at async /tmp/.mount_BitfinQm4x2w/resources/app/bfx-reports-framework/workers/loc.api/sync/dao/dao.better.sqlite.js:204:14
    at async BetterSqliteDAO._beginTrans (/tmp/.mount_BitfinQm4x2w/resources/app/bfx-reports-framework/workers/loc.api/sync/dao/dao.better.sqlite.js:212:19)
    at async BetterSqliteDAO.insertElemsToDb (/tmp/.mount_BitfinQm4x2w/resources/app/bfx-reports-framework/workers/loc.api/sync/dao/dao.better.sqlite.js:836:5)
    at async DataInserter._updateApiDataArrObjTypeToDb (/tmp/.mount_BitfinQm4x2w/resources/app/bfx-reports-framework/workers/loc.api/sync/data.inserter/index.js:843:5)
    at async DataInserter._updateApiData (/tmp/.mount_BitfinQm4x2w/resources/app/bfx-reports-framework/workers/loc.api/sync/data.inserter/index.js:739:7)
    at async DataInserter._insertNewPublicDataToDb (/tmp/.mount_BitfinQm4x2w/resources/app/bfx-reports-framework/workers/loc.api/sync/data.inserter/index.js:310:11)
    at async DataInserter.insertNewDataToDbMultiUser (/tmp/.mount_BitfinQm4x2w/resources/app/bfx-reports-framework/workers/loc.api/sync/data.inserter/index.js:229:9)
```

---

| Debug info | |
| :--- | :--- |
| Version | 4.8.1 |
| Commit Hash | de0740783d9e484239446aa3c7d806bd6803b2c3 |
| Commit Date | 2023-06-22T11:44:00Z |
| Electron | 21.3.3 |
| Chrome | 106.0.5249.199 |
| Node.js | 16.16.0 |
| V8 | 10.6.194.26-electron.0 |
| OS version | 22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jun 7 15:06:04 UTC 20 |
| OS release | Linux x64 5.19.0-45-generic |
| CPUs | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz x 16 |
| RAM | 15.26GB (8.75GB free) |
| App RAM limit | 2072Mb (10.92MB used) |
| Is BFX API Staging used | No |

<details>

<summary>Main log</summary>

```vim
    at async BetterSqliteDAO._proccesTrans (/tmp/.mount_BitfinQm4x2w/resources/app/bfx-reports-framework/workers/loc.api/sync/dao/dao.better.sqlite.js
    at async /tmp/.mount_BitfinQm4x2w/resources/app/bfx-reports-framework/workers/loc.api/sync/dao/helpers/manage-transaction/index.js:14:12
    at async module.exports (/tmp/.mount_BitfinQm4x2w/resources/app/bfx-reports-framework/workers/loc.api/sync/dao/helpers/manage-transaction/index.js:20:17)
    at async /tmp/.mount_BitfinQm4x2w/resources/app/bfx-reports-framework/workers/loc.api/sync/dao/dao.better.sqlite.js:204:14
    at async BetterSqliteDAO._beginTrans (/tmp/.mount_BitfinQm4x2w/resources/app/bfx-reports-framework/workers/loc.api/sync/dao/dao.better.sqlite.js:212:19)
    at async BetterSqliteDAO.insertElemsToDb (/tmp/.mount_BitfinQm4x2w/resources/app/bfx-reports-framework/workers/loc.api/sync/dao/dao.better.sqlite.js:836:5)
    at async DataInserter._updateApiDataArrObjTypeToDb (/tmp/.mount_BitfinQm4x2w/resources/app/bfx-reports-framework/workers/loc.api/sync/data.inserter/index.js:843:5)
    at async DataInserter._updateApiData (/tmp/.mount_BitfinQm4x2w/resources/app/bfx-reports-framework/workers/loc.api/sync/data.inserter/index.js:739:7)
    at async DataInserter._insertNewPublicDataToDb (/tmp/.mount_BitfinQm4x2w/resources/app/bfx-reports-framework/workers/loc.api/sync/data.inserter/index.js:310:11)
    at async DataInserter.insertNewDataToDbMultiUser (/tmp/.mount_BitfinQm4x2w/resources/app/bfx-reports-framework/workers/loc.api/sync/data.inserter/index.js:229:9)

```

</details>

<details>

<summary>Worker errors</summary>

```vim
    at async BetterSqliteDAO._proccesTrans (/tmp/.mount_BitfinQm4x2w/resources/app/bfx-reports-framework/workers/loc.api/sync/dao/dao.better.sqlite.js
    at async /tmp/.mount_BitfinQm4x2w/resources/app/bfx-reports-framework/workers/loc.api/sync/dao/helpers/manage-transaction/index.js:14:12
    at async module.exports (/tmp/.mount_BitfinQm4x2w/resources/app/bfx-reports-framework/workers/loc.api/sync/dao/helpers/manage-transaction/index.js:20:17)
    at async /tmp/.mount_BitfinQm4x2w/resources/app/bfx-reports-framework/workers/loc.api/sync/dao/dao.better.sqlite.js:204:14
    at async BetterSqliteDAO._beginTrans (/tmp/.mount_BitfinQm4x2w/resources/app/bfx-reports-framework/workers/loc.api/sync/dao/dao.better.sqlite.js:212:19)
    at async BetterSqliteDAO.insertElemsToDb (/tmp/.mount_BitfinQm4x2w/resources/app/bfx-reports-framework/workers/loc.api/sync/dao/dao.better.sqlite.js:836:5)
    at async DataInserter._updateApiDataArrObjTypeToDb (/tmp/.mount_BitfinQm4x2w/resources/app/bfx-reports-framework/workers/loc.api/sync/data.inserter/index.js:843:5)
    at async DataInserter._updateApiData (/tmp/.mount_BitfinQm4x2w/resources/app/bfx-reports-framework/workers/loc.api/sync/data.inserter/index.js:739:7)
    at async DataInserter._insertNewPublicDataToDb (/tmp/.mount_BitfinQm4x2w/resources/app/bfx-reports-framework/workers/loc.api/sync/data.inserter/index.js:310:11)
    at async DataInserter.insertNewDataToDbMultiUser (/tmp/.mount_BitfinQm4x2w/resources/app/bfx-reports-framework/workers/loc.api/sync/data.inserter/index.js:229:9)

```

</details>

<details>

<summary>Worker exceptions</summary>

```vim
Empty
```

</details>

---

*The issue was opened from the electron app*

**Comment by ZIMkaRU** [comment]
Fixed https://github.com/bitfinexcom/bfx-reports-framework/pull/311
