### ISSUE TITLE
[BUG REPORT]

### ISSUE THREAD

**Issue by Spaicho** [bitfinexcom/bfx-report-electron#222]
An error occurred

```vim
WORKER:ERROR [2023-07-06T13:12:01.229Z] PROGRESS:SYNC: StatusCodeError: 429 - ["error",11010,"ratelimit: error"]
    at new StatusCodeError (C:/Users/LENOVO/AppData/Local/Programs/bfx-report-electron/resources/app/bfx-reports-framework/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (C:/Users/LENOVO/AppData/Local/Programs/bfx-report-electron/resources/app/bfx-reports-framework/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (C:/Users/LENOVO/AppData/Local/Programs/bfx-report-electron/resources/app/bfx-reports-framework/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (C:/Users/LENOVO/AppData/Local/Programs/bfx-report-electron/resources/app/bfx-reports-framework/node_modules/bfx-api-node-rest/node_modules/request/request.js:198:22)
    at Request.<anonymous> (C:/Users/LENOVO/AppData/Local/Programs/bfx-report-electron/resources/app/bfx-reports-framework/node_modules/bfx-api-node-rest/node_modules/request/request.js:1035:10)
    at IncomingMessage.<anonymous> (C:/Users/LENOVO/AppData/Local/Programs/bfx-report-electron/resources/app/bfx-reports-framework/node_modules/bfx-api-node-rest/node_modules/request/request.js:962:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

```

---

| Debug info | |
| :--- | :--- |
| Version | 3.7.4 |
| Commit Hash | 61d3ac8ff807be2207f18a2ff20aeb70f94bc9b0 |
| Commit Date | 2022-08-11T10:07:58Z |
| Electron | 13.6.9 |
| Chrome | 91.0.4472.164 |
| Node.js | 14.16.0 |
| V8 | 9.1.269.40-electron.0 |
| OS version | Windows 10 Pro |
| OS release | Windows_NT x64 10.0.19045 |
| CPUs | Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz x 4 |
| RAM | 7.86GB (1.33GB free) |
| App RAM limit | 2072Mb (8.93MB used) |

<details>

<summary>Main log</summary>

```vim

```

</details>

<details>

<summary>Worker errors</summary>

```vim

```

</details>

<details>

<summary>Worker exceptions</summary>

```vim

```

</details>

---

*The issue was opened from the electron app*

**Comment by ZIMkaRU** [comment]
thanks for report, known issue, we are working on it

**Comment by ezewer** [comment]
issue should be solved, would re open if needed.
