### ISSUE TITLE
[BUG REPORT] AppInitializationError: ERR_APP_HAS_NOT_INITIALIZED

### ISSUE THREAD

**Issue by KingjZhang** [bitfinexcom/bfx-report-electron#227]
An error occurred

```vim
AppInitializationError: ERR_APP_HAS_NOT_INITIALIZED
    at Timeout.<anonymous> (C:/Users/ddd/AppData/Local/Programs/bfx-report-electron/resources/app/src/initialize-app.js:107:16)
```

---

| Debug info | |
| :--- | :--- |
| Version | 4.9.1 |
| Commit Hash | dc139dc2bbadfc44f6c0839462e3ab73837e714c |
| Commit Date | 2023-07-12T08:49:31Z |
| Electron | 21.3.3 |
| Chrome | 106.0.5249.199 |
| Node.js | 16.16.0 |
| V8 | 10.6.194.26-electron.0 |
| OS version | Windows 10 Pro |
| OS release | Windows_NT x64 10.0.22623 |
| CPUs | AMD Ryzen 9 5950X 16-Core Processor             x 32 |
| RAM | 63.93GB (39.88GB free) |
| App RAM limit | 4095.75Mb (10.68MB used) |
| Is BFX API Staging used | No |

<details>

<summary>Main log</summary>

```vim
[2023-07-13 23:02:18.563] [error
[2023-07-13 23:02:18.564] [error] Error: ENOENT: no such file or directory, open 'C:/Users/ahcz0/AppData/Roaming/Bitfinex Report/logs/exceptions-worker.log'
[2023-07-13 23:26:19.445] [error] AppInitializationError: ERR_APP_HAS_NOT_INITIALIZED
    at Timeout.<anonymous> (C:/Users/ahcz0/AppData/Local/Programs/bfx-report-electron/resources/app/src/initialize-app.js:107:16)

```

</details>

<details>

<summary>Worker errors</summary>

```vim
Log file read error
```

</details>

<details>

<summary>Worker exceptions</summary>

```vim
Log file read error
```

</details>

---

*The issue was opened from the electron app*

**Comment by KingjZhang** [comment]
I try to use another PC, and it works now.
