### ISSUE TITLE
[BUG REPORT]

### ISSUE THREAD

**Issue by PetrDlouhy** [bitfinexcom/bfx-report-electron#233]
An error occurred

```vim
WORKER:ERROR [2023-08-07T09:29:44.894Z] PROGRESS:SYNC: Error: HTTP code 500 Internal Server Error
    at Proxy._apiError (/tmp/.mount_BitfinKpN0Kn/resources/app/bfx-reports-framework/node_modules/bfx-api-node-rest/lib/rest2.js:159:17)
    at /tmp/.mount_BitfinKpN0Kn/resources/app/bfx-reports-framework/node_modules/bfx-report/workers/loc.api/helpers/get-rest.js:51:19
    at BfxApiRouter.route (/tmp/.mount_BitfinKpN0Kn/resources/app/bfx-reports-framework/workers/loc.api/bfx.api.router/index.js:69:14)
    at _route (/tmp/.mount_BitfinKpN0Kn/resources/app/bfx-reports-framework/node_modules/bfx-report/workers/loc.api/helpers/get-rest.js:49:23)
    at Object.apply (/tmp/.mount_BitfinKpN0Kn/resources/app/bfx-reports-framework/node_modules/bfx-report/workers/loc.api/helpers/get-rest.js:121:27)
    at Proxy._request (/tmp/.mount_BitfinKpN0Kn/resources/app/bfx-reports-framework/node_modules/bfx-api-node-rest/lib/rest2.js:148:26)
    at async _asyncApplyHook (/tmp/.mount_BitfinKpN0Kn/resources/app/bfx-reports-framework/node_modules/bfx-report/workers/loc.api/helpers/get-rest.js:65:21)
    at async _asyncApplyHook (/tmp/.mount_BitfinKpN0Kn/resources/app/bfx-reports-framework/node_modules/bfx-report/workers/loc.api/helpers/get-rest.js:65:21)
    at async _asyncApplyHook (/tmp/.mount_BitfinKpN0Kn/resources/app/bfx-reports-framework/node_modules/bfx-report/workers/loc.api/helpers/get-rest.js:65:21)
    at async _getResAndParams (/tmp/.mount_BitfinKpN0Kn/resources/app/bfx-reports-framework/node_modules/bfx-report/workers/loc.api/helpers/prepare-response/index.js:52:18)
    at async FrameworkReportService._prepareApiResponse (/tmp/.mount_BitfinKpN0Kn/resources/app/bfx-reports-framework/node_modules/bfx-report/workers/loc.api/helpers/prepare-response/index.js:150:19)
    at async ApiMiddleware.request (/tmp/.mount_BitfinKpN0Kn/resources/app/bfx-reports-framework/workers/loc.api/sync/data.inserter/api.middleware/index.js:32:20)
    at async DataInserter.getDataFromApi (/tmp/.mount_BitfinKpN0Kn/resources/app/bfx-reports-framework/node_modules/bfx-report/workers/loc.api/helpers/get-data-from-api.js:93:15)
    at async DataInserter._insertApiDataArrObjTypeToDb (/tmp/.mount_BitfinKpN0Kn/resources/app/bfx-reports-framework/workers/loc.api/sync/data.inserter/index.js:544:11)
    at async DataInserter._insertApiData (/tmp/.mount_BitfinKpN0Kn/resources/app/bfx-reports-framework/workers/loc.api/sync/data.inserter/index.js:461:7)
```

---

| Debug info | |
| :--- | :--- |
| Version | 4.9.2 |
| Commit Hash | c6dca30e88b31b00e0963d6ce1f0ba1c1bda5df3 |
| Commit Date | 2023-08-02T09:24:10Z |
| Electron | 21.3.3 |
| Chrome | 106.0.5249.199 |
| Node.js | 16.16.0 |
| V8 | 10.6.194.26-electron.0 |
| OS version | Ubuntu SMP PREEMPT_DYNAMIC Mon Jul 10 23:39:54 UTC 2023 |
| OS release | Linux x64 6.2.0-26-generic |
| CPUs | Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz x 8 |
| RAM | 30.26GB (12.96GB free) |
| App RAM limit | 4095.75Mb (13.59MB used) |
| Is BFX API Staging used | No |

<details>

<summary>Main log</summary>

```vim
    at Proxy._request (/tmp/.mount_BitfinKpN0Kn/resources/app/bfx-reports-framework/node_modules/bfx-api-node-rest/lib
    at async _asyncApplyHook (/tmp/.mount_BitfinKpN0Kn/resources/app/bfx-reports-framework/node_modules/bfx-report/workers/loc.api/helpers/get-rest.js:65:21)
    at async _asyncApplyHook (/tmp/.mount_BitfinKpN0Kn/resources/app/bfx-reports-framework/node_modules/bfx-report/workers/loc.api/helpers/get-rest.js:65:21)
    at async _asyncApplyHook (/tmp/.mount_BitfinKpN0Kn/resources/app/bfx-reports-framework/node_modules/bfx-report/workers/loc.api/helpers/get-rest.js:65:21)
    at async _getResAndParams (/tmp/.mount_BitfinKpN0Kn/resources/app/bfx-reports-framework/node_modules/bfx-report/workers/loc.api/helpers/prepare-response/index.js:52:18)
    at async FrameworkReportService._prepareApiResponse (/tmp/.mount_BitfinKpN0Kn/resources/app/bfx-reports-framework/node_modules/bfx-report/workers/loc.api/helpers/prepare-response/index.js:150:19)
    at async ApiMiddleware.request (/tmp/.mount_BitfinKpN0Kn/resources/app/bfx-reports-framework/workers/loc.api/sync/data.inserter/api.middleware/index.js:32:20)
    at async DataInserter.getDataFromApi (/tmp/.mount_BitfinKpN0Kn/resources/app/bfx-reports-framework/node_modules/bfx-report/workers/loc.api/helpers/get-data-from-api.js:93:15)
    at async DataInserter._insertApiDataArrObjTypeToDb (/tmp/.mount_BitfinKpN0Kn/resources/app/bfx-reports-framework/workers/loc.api/sync/data.inserter/index.js:544:11)
    at async DataInserter._insertApiData (/tmp/.mount_BitfinKpN0Kn/resources/app/bfx-reports-framework/workers/loc.api/sync/data.inserter/index.js:461:7)

```

</details>

<details>

<summary>Worker errors</summary>

```vim
    at Proxy._request (/tmp/.mount_B
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async _asyncApplyHook (/tmp/.mount_BitfinKpN0Kn/resources/app/bfx-reports-framework/node_modules/bfx-report/workers/loc.api/helpers/get-rest.js:65:21)
    at async _asyncApplyHook (/tmp/.mount_BitfinKpN0Kn/resources/app/bfx-reports-framework/node_modules/bfx-report/workers/loc.api/helpers/get-rest.js:65:21)
    at async _asyncApplyHook (/tmp/.mount_BitfinKpN0Kn/resources/app/bfx-reports-framework/node_modules/bfx-report/workers/loc.api/helpers/get-rest.js:65:21)
    at async _getResAndParams (/tmp/.mount_BitfinKpN0Kn/resources/app/bfx-reports-framework/node_modules/bfx-report/workers/loc.api/helpers/prepare-response/index.js:52:18)
    at async FrameworkReportService._prepareApiResponse (/tmp/.mount_BitfinKpN0Kn/resources/app/bfx-reports-framework/node_modules/bfx-report/workers/loc.api/helpers/prepare-response/index.js:150:19)
    at async ApiMiddleware.request (/tmp/.mount_BitfinKpN0Kn/resources/app/bfx-reports-framework/workers/loc.api/sync/data.inserter/api.middleware/index.js:32:20)
    at async DataInserter.getDataFromApi (/tmp/.mount_BitfinKpN0Kn/resources/app/bfx-reports-framework/node_modules/bfx-report/workers/loc.api/helpers/get-data-from-api.js:93:15)
    at async DataInserter._insertApiDataArrObjTypeToDb (/tmp/.mount_BitfinKpN0Kn/resources/app/bfx-reports-framework/workers/loc.api/sync/data.inserter/index.js:544:11)
    at async DataInserter._insertApiData (/tmp/.mount_BitfinKpN0Kn/resources/app/bfx-reports-framework/workers/loc.api/sync/data.inserter/index.js:461:7)

```

</details>

<details>

<summary>Worker exceptions</summary>

```vim
Empty
```

</details>

---

*The issue was opened from the electron app*

**Comment by ZIMkaRU** [comment]
thanks for reporting, we are investigating how we can fix it
related to https://github.com/bitfinexcom/bfx-report-electron/issues/232

**Comment by ZIMkaRU** [comment]
we've sent a patch
could you try the latest version of the app
https://github.com/bitfinexcom/bfx-report-electron/releases/tag/v4.9.3
