### ISSUE TITLE
[BUG REPORT]

### ISSUE THREAD

**Issue by PetrDlouhy** [bitfinexcom/bfx-report-electron#246]
An error occurred

```vim
WORKER:ERROR [2023-08-29T21:37:38.118Z]     request to https://api-pub.bitfinex.com/v2/auth/r/info/user failed, reason: getaddrinfo ENOTFOUND api-pub.bitfinex.com    
  - METHOD_NAME: verifyUser    
  - STATUS_CODE: 500    
  - STATUS_MESSAGE: Internal Server Error        
  - STACK_TRACE FetchError: request to https://api-pub.bitfinex.com/v2/auth/r/info/user failed, reason: getaddrinfo ENOTFOUND api-pub.bitfinex.com
    at ClientRequest.<anonymous> (/tmp/.mount_BitfinRyhkjg/resources/app/bfx-reports-framework/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:527:28)
    at TLSSocket.socketErrorListener (node:_http_client:454:9)
    at TLSSocket.emit (node:events:527:28)
```

---

| Debug info | |
| :--- | :--- |
| Version | 4.10.0 |
| Commit Hash | 49d2c919d82710be9a6ef5271af7a4b62c0702b7 |
| Commit Date | 2023-08-23T09:51:15Z |
| Electron | 21.3.3 |
| Chrome | 106.0.5249.199 |
| Node.js | 16.16.0 |
| V8 | 10.6.194.26-electron.0 |
| OS version | Ubuntu SMP PREEMPT_DYNAMIC Mon Jul 10 23:39:54 UTC 2023 |
| OS release | Linux x64 6.2.0-26-generic |
| CPUs | Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz x 8 |
| RAM | 30.26GB (7.48GB free) |
| App RAM limit | 4095.75Mb (15.71MB used) |
| Is BFX API Staging used | No |

<details>

<summary>Main log</summary>

```vim
    at async DataInserter._insertApiDataArrObjTypeToDb (/tmp/.mount
    at async DataInserter._insertApiData (/tmp/.mount_BitfinKpN0Kn/resources/app/bfx-reports-framework/workers/loc.api/sync/data.inserter/index.js:461:7)
[2023-08-07 13:15:22.363] [error] WORKER:ERROR [2023-08-07T11:15:22.359Z]     request to https://api-pub.bitfinex.com/v2/auth/r/info/user failed, reason: getaddrinfo ENOTFOUND api-pub.bitfinex.com    
  - METHOD_NAME: verifyUser    
  - STATUS_CODE: 500    
  - STATUS_MESSAGE: Internal Server Error        
  - STACK_TRACE FetchError: request to https://api-pub.bitfinex.com/v2/auth/r/info/user failed, reason: getaddrinfo ENOTFOUND api-pub.bitfinex.com
    at ClientRequest.<anonymous> (/tmp/.mount_BitfinKpN0Kn/resources/app/bfx-reports-framework/node_modules/node-fetch/lib/index.js:1505:11)
    at ClientRequest.emit (node:events:527:28)
    at TLSSocket.socketErrorListener (node:_http_client:454:9)
    at TLSSocket.emit (node:events:527:28)
[2023-08-29 23:37:38.111] [error] WORKER:ERROR [2023-08-29T21:37:38.107Z]     request to https://api-pub.bitfinex.com/v2/auth/r/info/user failed, reason: getaddrinfo ENOTFOUND api-pub.bitfinex.com    
  - METHOD_NAME: verifyUser    
  - STATUS_CODE: 500    
  - STATUS_MESSAGE: Internal Server Error        
  - STACK_TRACE FetchError: request to https://api-pub.bitfinex.com/v2/auth/r/info/user failed, reason: getaddrinfo ENOTFOUND api-pub.bitfinex.com
    at ClientRequest.<anonymous> (/tmp/.mount_BitfinRyhkjg/resources/app/bfx-reports-framework/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:527:28)
    at TLSSocket.socketErrorListener (node:_http_client:454:9)
    at TLSSocket.emit (node:events:527:28)
[2023-08-29 23:37:38.138] [error] WORKER:ERROR [2023-08-29T21:37:38.118Z]     request to https://api-pub.bitfinex.com/v2/auth/r/info/user failed, reason: getaddrinfo ENOTFOUND api-pub.bitfinex.com    
  - METHOD_NAME: verifyUser    
  - STATUS_CODE: 500    
  - STATUS_MESSAGE: Internal Server Error        
  - STACK_TRACE FetchError: request to https://api-pub.bitfinex.com/v2/auth/r/info/user failed, reason: getaddrinfo ENOTFOUND api-pub.bitfinex.com
    at ClientRequest.<anonymous> (/tmp/.mount_BitfinRyhkjg/resources/app/bfx-reports-framework/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:527:28)
    at TLSSocket.socketErrorListener (node:_http_client:454:9)
    at TLSSocket.emit (node:events:527:28)

```

</details>

<details>

<summary>Worker errors</summary>

```vim
  - STACK_TRACE FetchError: request to https://api-pub.bitfinex.com/v2/auth/r/info/user failed, reason: getaddrinfo ENOTFOUND api-pub.bitf
    at ClientRequest.<anonymous> (/tmp/.mount_BitfinKpN0Kn/resources/app/bfx-reports-framework/node_modules/node-fetch/lib/index.js:1505:11)
    at ClientRequest.emit (node:events:527:28)
    at TLSSocket.socketErrorListener (node:_http_client:454:9)
    at TLSSocket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
WORKER:ERROR [2023-08-29T21:37:38.107Z]     request to https://api-pub.bitfinex.com/v2/auth/r/info/user failed, reason: getaddrinfo ENOTFOUND api-pub.bitfinex.com    
  - METHOD_NAME: verifyUser    
  - STATUS_CODE: 500    
  - STATUS_MESSAGE: Internal Server Error        
  - STACK_TRACE FetchError: request to https://api-pub.bitfinex.com/v2/auth/r/info/user failed, reason: getaddrinfo ENOTFOUND api-pub.bitfinex.com
    at ClientRequest.<anonymous> (/tmp/.mount_BitfinRyhkjg/resources/app/bfx-reports-framework/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:527:28)
    at TLSSocket.socketErrorListener (node:_http_client:454:9)
    at TLSSocket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
WORKER:ERROR [2023-08-29T21:37:38.118Z]     request to https://api-pub.bitfinex.com/v2/auth/r/info/user failed, reason: getaddrinfo ENOTFOUND api-pub.bitfinex.com    
  - METHOD_NAME: verifyUser    
  - STATUS_CODE: 500    
  - STATUS_MESSAGE: Internal Server Error        
  - STACK_TRACE FetchError: request to https://api-pub.bitfinex.com/v2/auth/r/info/user failed, reason: getaddrinfo ENOTFOUND api-pub.bitfinex.com
    at ClientRequest.<anonymous> (/tmp/.mount_BitfinRyhkjg/resources/app/bfx-reports-framework/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:527:28)
    at TLSSocket.socketErrorListener (node:_http_client:454:9)
    at TLSSocket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)

```

</details>

<details>

<summary>Worker exceptions</summary>

```vim
Empty
```

</details>

---

*The issue was opened from the electron app*

**Comment by ezewer** [comment]
Hi @PetrDlouhy has this been solved
