### ISSUE TITLE
[BUG REPORT] database is locked

### ISSUE THREAD

**Issue by ezewer** [bitfinexcom/bfx-report-electron#248]
If keep running for some time, this occurs: 

```vim
WORKER:ERROR [2023-09-01T08:00:29.312Z] PROGRESS:SYNC:SET: SqliteError: database is locked
    at _runStm (/tmp/.mount_BitfinlH0xEo/resources/app/bfx-reports-framework/workers/loc.api/sync/dao/sqlite-worker/db-worker-actions/action-update-record-of.js:13:11)
    at /tmp/.mount_BitfinlH0xEo/resources/app/bfx-reports-framework/workers/loc.api/sync/dao/sqlite-worker/db-worker-actions/action-update-record-of.js:66:12
    at sqliteTransaction (/tmp/.mount_BitfinlH0xEo/resources/app/bfx-reports-framework/node_modules/better-sqlite3/lib/methods/transaction.js:65:24)
    at module.exports [as UPDATE_RECORD_OF] (/tmp/.mount_BitfinlH0xEo/resources/app/bfx-reports-framework/workers/loc.api/sync/dao/sqlite-worker/db-worker-actions/action-update-record-of.js:69:10)
    at module.exports (/tmp/.mount_BitfinlH0xEo/resources/app/bfx-reports-framework/workers/loc.api/sync/dao/sqlite-worker/db-worker-actions/index.js:18:31)
    at /tmp/.mount_BitfinlH0xEo/resources/app/bfx-reports-framework/workers/loc.api/sync/dao/dao.better.sqlite.js:126:20
    at async BetterSqliteDAO.query (/tmp/.mount_BitfinlH0xEo/resources/app/bfx-reports-framework/workers/loc.api/sync/dao/dao.better.sqlite.js:132:19)
    at async BetterSqliteDAO.updateRecordOf (/tmp/.mount_BitfinlH0xEo/resources/app/bfx-reports-framework/workers/loc.api/sync/dao/dao.better.sqlite.js:1163:17)
    at async Progress.setProgress (/tmp/.mount_BitfinlH0xEo/resources/app/bfx-reports-framework/workers/loc.api/sync/progress/index.js:56:7)
    at async SyncQueue.setProgress (/tmp/.mount_BitfinlH0xEo/resources/app/bfx-reports-framework/workers/loc.api/sync/sync.queue/index.js:440:5)
    at async SyncQueue._asyncProgressHandler (/tmp/.mount_BitfinlH0xEo/resources/app/bfx-reports-framework/workers/loc.api/sync/sync.queue/index.js:433:7)
```

---

| Debug info | |
| :--- | :--- |
| Version | 4.10.0 |
| Commit Hash | 49d2c919d82710be9a6ef5271af7a4b62c0702b7 |
| Commit Date | 2023-08-23T09:51:15Z |
| Electron | 21.3.3 |
| Chrome | 106.0.5249.199 |
| Node.js | 16.16.0 |
| V8 | 10.6.194.26-electron.0 |
| OS version | Ubuntu SMP PREEMPT_DYNAMIC Mon Jul 10 18:24:29 UTC 2023 |
| OS release | Linux x64 5.19.0-50-generic |
| CPUs | 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz x 16 |
| RAM | 15.26GB (6.23GB free) |
| App RAM limit | 2072Mb (14.43MB used) |
| Is BFX API Staging used | No |

<details>

<summary>Main log</summary>

```vim
    at sqliteTransaction (/tmp/.mount_BitfinlH0xEo/resources/app/bfx-reports-fr
    at module.exports [as UPDATE_RECORD_OF] (/tmp/.mount_BitfinlH0xEo/resources/app/bfx-reports-framework/workers/loc.api/sync/dao/sqlite-worker/db-worker-actions/action-update-record-of.js:69:10)
    at module.exports (/tmp/.mount_BitfinlH0xEo/resources/app/bfx-reports-framework/workers/loc.api/sync/dao/sqlite-worker/db-worker-actions/index.js:18:31)
    at /tmp/.mount_BitfinlH0xEo/resources/app/bfx-reports-framework/workers/loc.api/sync/dao/dao.better.sqlite.js:126:20
    at async BetterSqliteDAO.query (/tmp/.mount_BitfinlH0xEo/resources/app/bfx-reports-framework/workers/loc.api/sync/dao/dao.better.sqlite.js:132:19)
    at async BetterSqliteDAO.updateRecordOf (/tmp/.mount_BitfinlH0xEo/resources/app/bfx-reports-framework/workers/loc.api/sync/dao/dao.better.sqlite.js:1163:17)
    at async Progress.setProgress (/tmp/.mount_BitfinlH0xEo/resources/app/bfx-reports-framework/workers/loc.api/sync/progress/index.js:56:7)
    at async SyncQueue.setProgress (/tmp/.mount_BitfinlH0xEo/resources/app/bfx-reports-framework/workers/loc.api/sync/sync.queue/index.js:440:5)
    at async SyncQueue._asyncProgressHandler (/tmp/.mount_BitfinlH0xEo/resources/app/bfx-reports-framework/workers/loc.api/sync/sync.queue/index.js:433:7)

```

</details>

<details>

<summary>Worker errors</summary>

```vim
    at sqliteTransaction (/tmp/.mount_BitfinlH0xEo/resources/app/bfx-reports-fr
    at module.exports [as UPDATE_RECORD_OF] (/tmp/.mount_BitfinlH0xEo/resources/app/bfx-reports-framework/workers/loc.api/sync/dao/sqlite-worker/db-worker-actions/action-update-record-of.js:69:10)
    at module.exports (/tmp/.mount_BitfinlH0xEo/resources/app/bfx-reports-framework/workers/loc.api/sync/dao/sqlite-worker/db-worker-actions/index.js:18:31)
    at /tmp/.mount_BitfinlH0xEo/resources/app/bfx-reports-framework/workers/loc.api/sync/dao/dao.better.sqlite.js:126:20
    at async BetterSqliteDAO.query (/tmp/.mount_BitfinlH0xEo/resources/app/bfx-reports-framework/workers/loc.api/sync/dao/dao.better.sqlite.js:132:19)
    at async BetterSqliteDAO.updateRecordOf (/tmp/.mount_BitfinlH0xEo/resources/app/bfx-reports-framework/workers/loc.api/sync/dao/dao.better.sqlite.js:1163:17)
    at async Progress.setProgress (/tmp/.mount_BitfinlH0xEo/resources/app/bfx-reports-framework/workers/loc.api/sync/progress/index.js:56:7)
    at async SyncQueue.setProgress (/tmp/.mount_BitfinlH0xEo/resources/app/bfx-reports-framework/workers/loc.api/sync/sync.queue/index.js:440:5)
    at async SyncQueue._asyncProgressHandler (/tmp/.mount_BitfinlH0xEo/resources/app/bfx-reports-framework/workers/loc.api/sync/sync.queue/index.js:433:7)

```

</details>

<details>

<summary>Worker exceptions</summary>

```vim
    at Writable.write (/tmp/.mount_Bitfinia6XOS/resources/app/bfx-reports-framework/node_modu
    at DerivedLogger.ondata (/tmp/.mount_Bitfinia6XOS/resources/app/bfx-reports-framework/node_modules/readable-stream/lib/_stream_readable.js:629:20)
    at DerivedLogger.emit (node:events:539:35)
    at addChunk (/tmp/.mount_Bitfinia6XOS/resources/app/bfx-reports-framework/node_modules/readable-stream/lib/_stream_readable.js:279:12)
    at readableAddChunk (/tmp/.mount_Bitfinia6XOS/resources/app/bfx-reports-framework/node_modules/readable-stream/lib/_stream_readable.js:262:11)
    at Readable.push (/tmp/.mount_Bitfinia6XOS/resources/app/bfx-reports-framework/node_modules/readable-stream/lib/_stream_readable.js:228:10)
    at Transform.push (/tmp/.mount_Bitfinia6XOS/resources/app/bfx-reports-framework/node_modules/readable-stream/lib/_stream_transform.js:132:32)
    at DerivedLogger._transform (/tmp/.mount_Bitfinia6XOS/resources/app/bfx-reports-framework/node_modules/winston/lib/winston/logger.js:305:12)
    at Transform._read (/tmp/.mount_Bitfinia6XOS/resources/app/bfx-reports-framework/node_modules/readable-stream/lib/_stream_transform.js:166:10)
    at Transform._write (/tmp/.mount_Bitfinia6XOS/resources/app/bfx-reports-framework/node_modules/readable-stream/lib/_stream_transform.js:155:83)

```

</details>

---

*The issue was opened from the electron app*

**Comment by ZIMkaRU** [comment]
for investigation, this [issue](https://github.com/WiseLibs/better-sqlite3/issues/597) of the `better-sqlite3` driver might be a reason
