### ISSUE TITLE
[BUG REPORT] Error: net::ERR_CONNECTION_CLOSED

### ISSUE THREAD

**Issue by Eric1232023** [bitfinexcom/bfx-report-electron#415]
An error occurred

```vim
Error: net::ERR_CONNECTION_CLOSED
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:7068)
```

---

| Debug info | |
| :--- | :--- |
| Version | 3.6.0 |
| Commit Hash | c5946bcd63b611ab574ba1cf7d12513f949ca357 |
| Commit Date | 2021-10-15T08:18:01Z |
| Electron | 13.4.0 |
| Chrome | 91.0.4472.164 |
| Node.js | 14.16.0 |
| V8 | 9.1.269.39-electron.0 |
| OS version | Windows 7 Professional Service Pack 1 |
| OS release | Windows_NT x64 6.1.7601 |
| CPUs | Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz x 4 |
| RAM | 7.88GB (4.47GB free) |
| App RAM limit | 2072Mb (10.39MB used) |

<details>

<summary>Main log</summary>

```vim
[2023-11-09 14:03:43.786] [error] Error: net::ERR_NAME_NOT_RESOLVED
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/
[2024-10-04 13:22:33.549] [error] Error: net::ERR_CONNECTION_CLOSED
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:7068)

```

</details>

<details>

<summary>Worker errors</summary>

```vim
WORKER:ERROR [2024-10-04T11:14:11.737Z] 	    Error: read ECONNRESET    
  - METHOD_NAME: getAccountSummary [PROTECTED]    
  - STATUS_CODE: 500    
  - STATUS_MESSAGE: Internal Server Error        
  - STACK_TRACE RequestError: Error: read ECONNRESET
    at new RequestError (C

```

</details>

<details>

<summary>Worker exceptions</summary>

```vim
Empty
```

</details>

---

*The issue was opened from the electron app*

**Comment by ZIMkaRU** [comment]
Could you re-install and try the latest release?
https://github.com/bitfinexcom/bfx-report-electron/releases/tag/v4.28.0
