### ISSUE TITLE
[BUG REPORT] Made a account but still no access

### ISSUE THREAD

**Issue by GardaHans** [bitfinexcom/bfx-report-electron#418]
An error occurred

```vim
Error: Failed to get 'documents' path
    at module.exports (C:/Users/hansh/AppData/Local/Programs/bfx-report-electron/resources/app/src/initialize-app.js:166:37)
    at async C:/Users/hansh/AppData/Local/Programs/bfx-report-electron/resources/app/index.js:42:7
```

---

| Debug info | |
| :--- | :--- |
| Version | 4.27.0 |
| Commit Hash | 715055cb398ce4c30b755306793c51d60594e6d1 |
| Commit Date | 2024-09-11T06:57:01Z |
| Electron | 27.3.5 |
| Chrome | 118.0.5993.159 |
| Node.js | 18.17.1 |
| V8 | 11.8.172.18-electron.0 |
| OS version | Windows 10 Pro |
| OS release | Windows_NT x64 10.0.22631 |
| CPUs | Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz x 8 |
| RAM | 15.79GB (7.1GB free) |
| App RAM limit | 4095.75Mb (10.56MB used) |
| Is BFX API Staging used | No |

<details>

<summary>Main log</summary>

```vim
[2024-09-12 16:09:42.443] [error] Error: Failed to get 'documents' path
    at module.exports (C:/Users/hansh/AppData/Local/Programs/bfx-report-electron/resources/app/src/initialize-app.js:166:37)
    at async C:/Users/hansh/AppData/Local/Programs/bfx-report-electron/resources/app/index.js:42:7

```

</details>

<details>

<summary>Worker errors</summary>

```vim
Log file read error
```

</details>

<details>

<summary>Worker exceptions</summary>

```vim
Log file read error
```

</details>

---

*The issue was opened from the electron app*

**Comment by ZIMkaRU** [comment]
This indicates that your Windows `documents` directory has been misconfigured
In Windows Explorer, right-click your `Documents` folder, then select properties -> location
There you can either set it to a valid location or reset it to the default
